import { stringify } from '../util/json.mjs';
import { hashBytes, hashManifest } from '../util/hash.mjs';
import { redact } from '../util/redact.mjs';
import { bullets, heading, paragraph, quote, section, STATUS_LABEL, table } from './markdown.mjs';
import { STATUS_MEANING } from '../rules/status.mjs';

const DISCLAIMER = [
  'This pack prepares technical evidence. It is not a conformity assessment under Article 32,',
  'not an EU declaration of conformity under Article 28, not a CE marking, and not legal advice.',
  'No statement here asserts that the product complies with Regulation (EU) 2024/2847.',
].join(' ');

function renderReadme({ assessment, manifest, sourceRegister }) {
  return section(
    heading(1, 'CRA technical evidence pack'),
    quote(DISCLAIMER),
    paragraph(`Generated by \`${assessment.tool.name}\` ${assessment.tool.version} using ruleset \`${assessment.ruleset.id}\` version ${assessment.ruleset.version}.`),
    heading(2, 'Subject'),
    table(['Field', 'Value'], [
      ['Product', assessment.subject.product],
      ['Version', assessment.subject.version],
      ['Commit', assessment.subject.commit],
      ['Working tree clean', assessment.subject.worktreeClean === null ? 'unknown' : String(assessment.subject.worktreeClean)],
      ['State fingerprint', assessment.subject.stateFingerprint],
      ['Generated at', assessment.generatedAt],
    ]),
    heading(2, 'What is in this pack'),
    table(['File', 'Purpose'], [
      ['`executive-summary.md`', 'What was verified, declared, missing, and what a human still has to decide.'],
      ['`annex-vii-map.md`', 'Coverage of the technical documentation content required by Annex VII.'],
      ['`evidence-index.md`', 'Every control, its status, its evidence and the exact provision it cites.'],
      ['`gaps.md`', 'Open gaps, ordered by priority, each with a remediation step.'],
      ['`product-profile.md`', 'The manufacturer declarations, separated from observations.'],
      ['`limitations.md`', 'What this pack does not establish.'],
      ['`assessment.json`', 'Structured source for every rendered document.'],
      ['`evidence-manifest.json`', 'One record per artefact read, with its hash and the commit it belongs to.'],
      ['`sbom.cdx.json`', 'CycloneDX bill of materials generated from the lockfile.'],
      ['`source-register.json`', 'The official sources this ruleset cites, with access dates and digests.'],
      ['`SHA256SUMS`', 'Digest of every file in this pack.'],
    ]),
    heading(2, 'How to reproduce it'),
    paragraph('From the analysed repository, at the same commit:'),
    paragraph('```sh\nnpx probative run . --out cra-evidence/\n```'),
    paragraph(`The run reads the repository, executes no project script and opens no network connection. Two runs at the same commit with the same product profile produce the same content, except for the \`generatedAt\` timestamps. Pin them with \`--now\` or \`SOURCE_DATE_EPOCH\` to obtain byte-identical output.`),
    heading(2, 'How to check it has not drifted'),
    paragraph('```sh\nnpx probative verify cra-evidence/\n```'),
    paragraph(`Verification recomputes every digest in \`SHA256SUMS\`, then compares the pack's commit and state fingerprint with the repository as it stands now. Evidence collected at another commit is reported as stale.`),
    heading(2, 'Sources'),
    bullets(sourceRegister.sources.map((source) => `${source.title} - ${source.url} (accessed ${source.accessedOn})`)),
    heading(2, 'Redaction'),
    paragraph(manifest.redaction.findings.length === 0
      ? 'No secret-shaped string was found in the collected material.'
      : `Redaction replaced ${manifest.redaction.findings.reduce((total, item) => total + item.count, 0)} secret-shaped string(s) before writing this pack.`),
  );
}

function renderExecutiveSummary({ assessment }) {
  const { summary } = assessment;
  const statusRows = Object.entries(summary.byStatus)
    .filter(([, count]) => count > 0)
    .map(([status, count]) => [STATUS_LABEL[status] ?? status, String(count), STATUS_MEANING[status]]);

  const topGaps = assessment.gaps.slice(0, 5).map((gap, index) => [
    String(index + 1), gap.priority, gap.id, gap.title, STATUS_LABEL[gap.status] ?? gap.status,
  ]);

  return section(
    heading(1, 'Executive summary'),
    quote(DISCLAIMER),
    paragraph(`${summary.controlsEvaluated} controls were evaluated against ruleset \`${assessment.ruleset.id}\` ${assessment.ruleset.version}. ${summary.openGaps} are open, of which ${summary.p0Gaps} are priority P0. ${summary.requiringExpertReview} require a determination this tool cannot make.`),
    heading(2, 'Evidence state'),
    table(['State', 'Controls', 'Meaning'], statusRows),
    heading(2, topGaps.length === 0 ? 'Gaps' : `The ${topGaps.length === 1 ? 'gap' : `${topGaps.length} gaps`} to close first`),
    topGaps.length > 0 ? table(['#', 'Priority', 'Control', 'Title', 'State'], topGaps) : paragraph('No open gap was recorded by this ruleset.'),
    heading(2, 'Decisions that need a competent reviewer'),
    assessment.expertReview.length > 0
      ? table(['Control', 'Title', 'State'], assessment.expertReview.map((item) => [item.id, item.title, STATUS_LABEL[item.status] ?? item.status]))
      : paragraph('None recorded.'),
    heading(2, 'Product profile'),
    paragraph(assessment.profile.present
      ? (assessment.profile.valid
        ? 'A product profile was found and is valid against its schema.'
        : `A product profile was found but has ${assessment.profile.schemaErrors.length} schema error(s); the declarations it carries are still reported, marked as declared.`)
      : 'No product profile was found. Every control that depends on a manufacturer declaration is reported as missing rather than failed. Run `probative profile init` to create one.'),
  );
}

function renderAnnexViiMap({ assessment, ruleset }) {
  // A control belongs to a point because it CITES it, not because its family
  // happens to sit under that section. Matching on the family would hide the
  // controls that speak to several points at once.
  const rows = ruleset.annexVii.map((entry) => {
    const controls = assessment.controls.filter((control) => control.citations
      .some((citation) => citation.locus === entry.locus || citation.locus.startsWith(`${entry.locus}.`)));
    const worst = controls.length === 0 ? 'not covered by this ruleset' : summariseStatuses(controls);
    return [entry.reference, entry.summary, controls.map((c) => c.id).join(', ') || '-', worst];
  });

  return section(
    heading(1, 'Annex VII coverage map'),
    quote(DISCLAIMER),
    paragraph('Annex VII lists the content of the technical documentation required by Article 31. This map shows, point by point, which controls speak to it and what this pack established. A point with no control is a point this tool does not cover; it is not a point that does not apply.'),
    table(['Annex VII point', 'Required content', 'Controls', 'State'], rows),
    heading(2, 'What a covered point still does not give you'),
    paragraph('A control against a point means this pack carries evidence or a declaration relevant to it. It does not mean the point of the technical documentation is written.'),
    bullets([
      'Point 1(c), photographs and internal layout: hardware only, and not applicable to a software product.',
      'Point 2(a), the system architecture description: a design document somebody has to write. Nothing detects it.',
      'Point 3, the cybersecurity risk assessment: only its existence, its date and its stated coverage of Annex I, Part I are recorded. The assessment itself is neither read nor judged.',
      'Point 5, harmonised standards: recorded as a declaration. At the date of this ruleset the harmonised standards under the Regulation are still being developed, so an empty list is the expected answer.',
      'Point 6, test reports: this tool detects that tests are configured in CI. It runs nothing and reads no run history, so no result here is a test report.',
      'Point 7, the EU declaration of conformity: drawn up by the manufacturer after a conformity assessment under Article 32. Only its URL is recorded.',
      'Point 8, the bill of materials on request: the pack generates one, but responding to a reasoned request from a market surveillance authority is a process, not a file.',
    ]),
  );
}

function summariseStatuses(controls) {
  const order = ['error', 'missing', 'stale', 'partial', 'needs_expert_review', 'declared', 'verified', 'not_applicable'];
  const worst = order.find((status) => controls.some((control) => control.status === status));
  const counts = controls.reduce((accumulator, control) => {
    accumulator[control.status] = (accumulator[control.status] ?? 0) + 1;
    return accumulator;
  }, {});
  const detail = Object.entries(counts).sort().map(([status, count]) => `${count} ${STATUS_LABEL[status] ?? status}`).join(', ');
  return `${STATUS_LABEL[worst] ?? worst} (${detail})`;
}

function renderEvidenceIndex({ assessment }) {
  const families = [...new Map(assessment.controls.map((control) => [control.family, control.familyTitle])).entries()];
  const parts = [
    heading(1, 'Evidence index'),
    quote(DISCLAIMER),
    paragraph('One entry per control: what was found, what it cites in the Regulation, and what it does not prove.'),
  ];

  for (const [familyId, familyTitle] of families) {
    const controls = assessment.controls.filter((control) => control.family === familyId);
    parts.push(heading(2, familyTitle));
    for (const control of controls) {
      parts.push(heading(3, `${control.id} - ${control.title}`));
      parts.push(table(['Field', 'Value'], [
        ['State', STATUS_LABEL[control.status] ?? control.status],
        ['Priority', control.priority],
        ['Cites', control.citations.map((citation) => citation.reference).join('; ')],
      ]));
      parts.push(paragraph(control.summary));
      if (control.findings.length > 0) {
        parts.push(table(['Observation', 'Value'], control.findings.map((item) => [item.label, item.detail ? `${item.value} (${item.detail})` : item.value])));
      }
      parts.push(paragraph(`**Limitations.** ${control.limitations}`));
      if (control.expertReviewWhen.length > 0) {
        parts.push(paragraph(`**Expert review.** ${control.expertReviewWhen.join('; ')}.`));
      }
      parts.push(heading(4, 'Provisions cited'));
      for (const citation of control.citations) {
        parts.push(paragraph(`*${citation.reference}*`));
        if (citation.text) parts.push(quote(citation.text));
      }
    }
  }
  return section(...parts);
}

function renderGaps({ assessment }) {
  const parts = [
    heading(1, 'Gaps'),
    quote(DISCLAIMER),
    paragraph('Ordered by priority, then by how far the evidence is from complete. A gap is an absence of evidence, not a finding of non-compliance.'),
  ];
  if (assessment.gaps.length === 0) {
    parts.push(paragraph('No open gap was recorded by this ruleset.'));
    return section(...parts);
  }
  parts.push(table(['Priority', 'Control', 'State', 'Gap'], assessment.gaps.map((gap) => [gap.priority, gap.id, STATUS_LABEL[gap.status] ?? gap.status, gap.title])));
  for (const gap of assessment.gaps) {
    parts.push(heading(2, `${gap.id} - ${gap.title}`));
    parts.push(table(['Field', 'Value'], [
      ['Priority', gap.priority],
      ['State', STATUS_LABEL[gap.status] ?? gap.status],
      ['Cites', gap.citations.join('; ')],
    ]));
    parts.push(paragraph(gap.summary));
    parts.push(paragraph(`**Next step.** ${gap.remediation}`));
  }
  return section(...parts);
}

function renderProductProfile({ assessment, profileResult, inventory }) {
  const observed = table(['Observation', 'Value'], [
    ['Package name', inventory.package.name],
    ['Package version', inventory.package.version],
    ['Declared license', inventory.package.license],
    ['Commit', inventory.git.commit],
    ['Working tree clean', inventory.git.dirty === null ? 'unknown' : String(!inventory.git.dirty)],
    ['Tags at HEAD', inventory.git.tagsAtHead.join(', ') || 'none'],
    ['Runtime components in the bill of materials', String(assessment.summary.controlsEvaluated > 0 ? (assessment.sbomComponentCount ?? '-') : '-')],
    ['Security policy', inventory.docs.securityPolicy.path ?? 'absent'],
    ['CI provider', inventory.ci.provider],
  ]);

  const parts = [
    heading(1, 'Product profile'),
    quote(DISCLAIMER),
    paragraph('Two kinds of statement appear below and they are never mixed. Observations were read from the repository. Declarations were written by the manufacturer and are reproduced as given.'),
    heading(2, 'Observed in the repository'),
    observed,
    heading(2, 'Declared by the manufacturer'),
  ];

  if (!profileResult.present) {
    parts.push(paragraph('No product profile file was found. Run `probative profile init` to create one, then fill it in.'));
    return section(...parts);
  }
  if (profileResult.errors.length > 0) {
    parts.push(paragraph(`The profile has ${profileResult.errors.length} schema error(s):`));
    parts.push(table(['Path', 'Problem'], profileResult.errors.map((error) => [error.path, error.message])));
  }
  const profile = profileResult.profile ?? {};
  parts.push(...renderDeclarationBlocks(profile));
  return section(...parts);
}

function renderDeclarationBlocks(profile) {
  const blocks = [
    ['Product', profile.product],
    ['Manufacturer', profile.manufacturer],
    ['Regulatory position', profile.regulatoryPosition],
    ['Support period', profile.supportPeriod],
    ['Vulnerability handling', profile.vulnerabilityHandling],
    ['Risk assessment', profile.riskAssessment],
    ['Technical documentation', profile.technicalDocumentation],
    ['User information', profile.userInformation],
  ];
  const parts = [];
  for (const [title, value] of blocks) {
    if (!value || typeof value !== 'object') continue;
    parts.push(heading(3, title));
    parts.push(table(['Field', 'Declared value'], flatten(value).map(([key, item]) => [key, item])));
  }
  return parts;
}

function flatten(value, prefix = '') {
  const rows = [];
  for (const [key, item] of Object.entries(value)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (item && typeof item === 'object' && !Array.isArray(item)) rows.push(...flatten(item, path));
    else if (Array.isArray(item)) rows.push([path, item.length === 0 ? 'none' : item.map((entry) => (typeof entry === 'object' ? JSON.stringify(entry) : String(entry))).join('; ')]);
    else rows.push([path, item === null || item === '' ? 'not declared' : String(item)]);
  }
  return rows;
}

/** What the walk was allowed to cover, and whether it needed all of it. */
function walkSentence(walk) {
  if (!walk) return 'The repository was walked in full.';
  const bounds = `at most ${walk.maxEntries} files and ${walk.maxDepth} levels of directory`;
  return walk.truncated
    ? `The repository walk is bounded to ${bounds}, and those bounds were reached: parts of the tree were not read, and the inventories say which are affected.`
    : `The repository walk is bounded to ${bounds}. It stopped because it ran out of tree, not because it reached them.`;
}

function renderLimitations({ assessment, ruleset, inventory }) {
  return section(
    heading(1, 'Limitations'),
    quote(DISCLAIMER),
    heading(2, 'What this pack is'),
    paragraph('An inventory of technical evidence that exists in a repository, plus the declarations a manufacturer made about the product. It is an input to the technical documentation required by Article 31, not that documentation.'),
    heading(2, 'What this ruleset does not cover'),
    bullets(ruleset.scope.doesNotCover),
    heading(2, 'How the evidence was obtained'),
    bullets([
      'The repository was read. No project script, test, build or install command was executed.',
      walkSentence(inventory.walk),
      'No network request was made. The bill of materials comes from the lockfile, not from a registry.',
      'Continuous integration workflows were scanned as text, not parsed as YAML. Every signal derived from them is a mention, not proven behaviour.',
      'Documents were matched by name and by keyword. A practice documented under a heading this tool does not recognise reads as absent.',
      'Manufacturer declarations were not verified. They carry the state Declared and nothing stronger.',
    ]),
    heading(2, 'What was not readable'),
    inventory.notes.length > 0 ? bullets(inventory.notes) : paragraph('Nothing was reported as unreadable during this run.'),
    heading(2, 'Freshness'),
    paragraph(assessment.subject.worktreeClean === false
      ? 'The working tree had uncommitted changes when this pack was produced. The evidence describes the working tree, not a commit that anyone else can retrieve.'
      : 'The evidence is bound to the commit named in the pack README. Regenerate the pack whenever the product changes; `probative verify` reports a pack collected at another commit as stale.'),
    heading(2, 'Applicability dates'),
    bullets([
      'Article 14, reporting of actively exploited vulnerabilities and severe incidents: applies from 11 September 2026.',
      'Chapter IV, notification of conformity assessment bodies: applies from 11 June 2026.',
      'The rest of the Regulation: applies from 11 December 2027.',
      'Source: Article 71(2) of Regulation (EU) 2024/2847.',
    ]),
  );
}

/**
 * Build every file of the pack. Returns a map of relative path to file content,
 * so the caller can write the whole tree atomically or inspect it in a test.
 */
export function renderPack({ assessment, manifest, sbom, inventory, profileResult, ruleset, sourceRegister }) {
  const annexVii = { annexVii: ruleset.annexViiIndex ?? [] };
  const files = {
    'README.md': renderReadme({ assessment, manifest, sourceRegister }),
    'executive-summary.md': renderExecutiveSummary({ assessment }),
    'annex-vii-map.md': renderAnnexViiMap({ assessment, ruleset: { annexVii: ruleset.annexViiIndex ?? [] } }),
    'evidence-index.md': renderEvidenceIndex({ assessment }),
    'gaps.md': renderGaps({ assessment }),
    'product-profile.md': renderProductProfile({ assessment, profileResult, inventory }),
    'limitations.md': renderLimitations({ assessment, ruleset, inventory }),
    'assessment.json': stringify(assessment),
    'evidence-manifest.json': stringify(manifest),
    'source-register.json': stringify(sourceRegister),
  };
  if (sbom) files['sbom.cdx.json'] = stringify(sbom);

  // Every string that reaches disk passes redaction one final time, including
  // the ones assembled from templates.
  const redactionFindings = [];
  for (const [path, content] of Object.entries(files)) {
    const outcome = redact(content);
    redactionFindings.push(...outcome.findings);
    files[path] = outcome.text;
  }

  const entries = Object.entries(files)
    .map(([path, content]) => ({ path, hash: hashBytes(content) }))
    .sort((a, b) => a.path.localeCompare(b.path));
  files['SHA256SUMS'] = `${entries.map((entry) => `${entry.hash.replace('sha256:', '')}  ${entry.path}`).join('\n')}\n`;
  files['pack.json'] = stringify({
    schemaVersion: '1.0.0',
    tool: assessment.tool,
    ruleset: { id: assessment.ruleset.id, version: assessment.ruleset.version },
    generatedAt: assessment.generatedAt,
    subject: assessment.subject,
    packDigest: hashManifest(entries),
    files: entries,
    finalRedactionFindings: redactionFindings.length,
  });
  return files;
}
